#!/bin/sh

### 6/5/2013:
### this is a work in progress... it's not currently production-worthy, or 
### even necessarily functional.

## example:
#   muntarsend -a rnelson -k fd:9c:78:0f:bd:58:e0:88:38:01:93:3b:ab:80:a5:93 -d dump test-upload
#  sends local file "test-upload" to the directory /rnelson/stor/dump , using the key provided


## set defaults in case they're not passed as arguments
MANTA_USER=ryancnelson
MANTA_KEY_ID=f3:04:66:7b:47:bc:40:f0:e6:e4:c2:01:39:23:a9:13
MANTA_URL=https://us-east.manta.joyent.com

while getopts a:d:k: opt; do
	case $opt in
	a)
	  MANTA_USER=$OPTARG
	  echo MANTA_USER = $MANTA_USER
	;;

	d) 
	  remotedir=$OPTARG
	  echo remotedir = $remotedir
	;;

	k)
	  MANTA_KEY=$OPTARG
	  echo MANTA_KEY = $MANTA_KEY
	;;

	\?)
	echo "Invalid option: -$OPTARG" >&2
	exit 1
	;;
	esac

done

shift $((OPTIND-1))

if [ -z $1 ] ; 
then 
	echo "zero length arg: must enter file argument" 
	exit 
fi

if [ ! -f $1 ] ; 
then 
	echo "arg not file: must enter file argument" 
	exit 
fi

file=$1

echo ------------------ $file

remotesize=$(mls -k $MANTA_KEY -a $MANTA_USER -j /${MANTA_USER}/stor/${remotedir}/${file} | json size ) 
if [ x$remotesize = "x" ] ; then remotesize=-1 ; fi

## if there's already something on the other side, calculate it's md5 hash
if [ x$remotesize != "x" ] ; then
	remotehash=$(mmd5 -k $MANTA_KEY -a $MANTA_USER /${MANTA_USER}/stor/${remotedir}/${file} | awk '{print $1}' ) 
fi

### should use "stat" here, instead of ls -la and awk
#localsize=$(ls -la $file  | awk '{print $5}' )
localsize=$(stat -f %z $file)

## it shouldn't be possible for the file to exist, but not have a size...
## eliminate this?
if [ x$localsize = "x" ] ; then localsize=-1 ; fi

## if there's something on the other side to compare it to, calculate the md5 on this side, too
if [ x$remotesize != "x" ] ; then
	localhash=$(cat ${file} | md5 ) 
fi

echo localsize = $localsize
echo remotesize = $remotesize
echo localhash = $localhash
echo remotehash = $remotehash
echo comparing sizes and hashes:
if [ $remotesize -eq $localsize ] && [ $remotehash = $localhash ] 
  then 
    echo "remote seems to be identical to local.  exiting."
    exit 0
fi
	

### this is my local copy of gnu tar... required for the "transform" option
/usr/local/bin/tar --transform='s/ /%20/g' -cvf /tmp/muntar-temp.tar "$file"  ; 

###/usr/local/bin/tar -cvf /tmp/muntar-temp.tar "$file"  ; 
muntar -u https://us-east.manta.joyent.com -k $MANTA_KEY -f /tmp/muntar-temp.tar /${MANTA_USER}/stor/${remotedir}
