#!/bin/sh

### 6/5/2013:
### this is a work in progress... it's not currently production-worthy, or 
### even necessarily functional.


## this currently requires you hold my private key.
## nothing in this script is sensitive information

## set defaults in case they're not passed as arguments
MANTA_USER=ryancnelson
MANTA_KEY_ID=f3:04:66:7b:47:bc:40:f0:e6:e4:c2:01:39:23:a9:13
MANTA_URL=https://us-east.manta.joyent.com

while getopts a:d:k: opt; do
	case $opt in
	a)
	  MANTA_USER=$OPTARG
	  echo MANTA_USER = $MANTA_USER
	;;

	d) 
	  remotedir=$OPTARG
	  echo remotedir = $remotedir
	;;

	k)
	  MANTA_KEY=$OPTARG
	  echo MANTA_KEY = $MANTA_KEY
	;;

	\?)
	echo "Invalid option: -$OPTARG" >&2
	exit 1
	;;
	esac

done

shift $((OPTIND-1))

if [ -z $1 ] ; 
then 
	echo "zero length arg: must enter file argument" 
	exit 
fi

if [ ! -f $1 ] ; 
then 
	echo "arg not file: must enter file argument" 
	exit 
fi

file=$1

echo ------------------ $file

remotesize=$(mls -k $MANTA_KEY -a $MANTA_USER -l /${MANTA_USER}/stor/${remotedir}/${file} | awk '{print $4}' ) 
if [ x$remotesize = "x" ] ; then remotesize=-1 ; fi

### should use "stat" here, instead of ls -la and awk
#localsize=$(ls -la $file  | awk '{print $5}' )
localsize=$(stat -f %z test-upload)
if [ x$localsize = "x" ] ; then localsize=-1 ; fi
echo localsize = $localsize
echo remotesize = $remotesize
if [ $remotesize -eq $localsize ] 
  then 
    echo "remote is same size as local.  exiting."
    exit 0
fi
	

### this is my local copy of gnu tar... required for the "transform" option
/usr/local/bin/tar --transform='s/ /%20/g' -cvf /tmp/muntar-temp.tar "$file"  ; 

###/usr/local/bin/tar -cvf /tmp/muntar-temp.tar "$file"  ; 
muntar -u https://us-east.manta.joyent.com -k $MANTA_KEY -f /tmp/muntar-temp.tar /${MANTA_USER}/stor/${remotedir}
